config/routes.rb
Rails.application.routes.draw do
  resources :channels do
    resources :messages, only: :create
  end
  root "channels#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/channel.rb
class Channel < ApplicationRecord
  has_many :messages, dependent: :destroy
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :channel

  after_commit on: :create do
    broadcast_append_to(
      channel,
      partial: "messages/message",
      locals: { message: self },
      target: "messages"
    )
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  attr_reader :channel
  alias current_channel channel

  helper_method :current_channel
end

app/controllers/channels_controller.rb
class ChannelsController < ApplicationController
  before_action :set_channel, only: %i[ show edit update destroy ]
  before_action :set_channels

  def index
    @channels = Channel.all
  end

  def show
    render action: :index
  end

  def new
    @channel = Channel.new
  end

  def edit
  end

  def create
    @channel = Channel.new(channel_params)

    if @channel.save
      redirect_to @channel, notice: "Channel was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @channel.update(channel_params)
      redirect_to @channel, notice: "Channel was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @channel.destroy
    redirect_to channels_url, notice: "Channel was successfully destroyed."
  end

  private
    def set_channels
      @channels = Channel.all.order(name: :asc)
    end

    def set_channel
      @channel = Channel.find(params[:id])
    end

    def channel_params
      params.require(:channel).permit(:name)
    end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_channel, only: %i[create]

  def create
    channel.messages.create(messages_params.merge(author: "unknown"))
    render partial: "messages/form"
  end

  private
    def set_channel
      @channel = Channel.find(params[:channel_id])
    end

    def messages_params
      params.require(:message).permit(:content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/channels/_channel.html.erb
<div id="<%= dom_id channel %>">
  <p class="<%= "font-bold" if channel == current_channel %>">
    <%= link_to "##{channel.name}", channel %>
  </p>
</div>

app/views/channels/_form.html.erb
<%= form_with(model: channel, class: "contents") do |form| %>
  <% if channel.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(channel.errors.count, "error") %> prohibited this channel from being saved:</h2>

      <ul>
        <% channel.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :name %>
    <%= form.text_field :name, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/channels/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing channel</h1>

  <%= render "form", channel: @channel %>

  <%= link_to "Show this channel", @channel, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to channels", channels_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/channels/index.html.erb
<div class="w-full">
  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Channels</h1>
  </div>

  <div id="channels" class="min-w-full">
    <div class="flex-1 p:2 sm:p-6 justify-between flex flex-col h-96">
      <div class="flex space-x-3 py-2 border-b-2 border-gray-200">
        <%= render @channels %>
      </div>
      <% if !current_channel %>
        <div class="flex justify-center">
          <div class="text-center">
            <h2 class="text-xl font-bold">Select a channel</h2>
            <p class="text-gray-600">
              You can select a channel to see the messages.
            </p>
          </div>
        </div>
      <% else %>
        <div id="messages" class="flex flex-col space-y-4 p-3 overflow-y-auto scrollbar-thumb-blue scrollbar-thumb-rounded scrollbar-track-blue-lighter scrollbar-w-2 scrolling-touch">
          <%= turbo_stream_from current_channel %>
          <%= render current_channel.messages.order(id: :asc)%>
        </div>
      <% end %>
    </div>
    <div class="border-t-2 border-gray-200 px-4 pt-4 mb-2 sm:mb-0">
      <%= render partial: "messages/form" if current_channel %>
    </div>
  </div>  
</div>

app/views/channels/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New channel</h1>

  <%= render "form", channel: @channel %>

  <%= link_to 'Back to channels', channels_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/channels/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @channel %>

    <%= link_to 'Edit this channel', edit_channel_path(@channel), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to 'Destroy this channel', channel_path(@channel), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to 'Back to channels', channels_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Channel Chat</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="container mx-auto mt-28 px-5 flex">
      <%= yield %>
    </main>
  </body>
</html>

app/views/messages/_form.html.erb
<turbo-frame id="<%= dom_id(current_channel, :form) %>">
  <%= form_for [current_channel, Message.new], html: { class: "relative flex" } do |f| %>
    <%= f.text_field :content,
      placeholder: "Message",
      class:"w-full focus:outline-none focus:placeholder-gray-400 text-gray-600 text-xs placeholder-gray-500 pl-6 bg-slate-300 rounded-full py-3"
    %>
      <div class="absolute right-0 items-center inset-y-0 hidden sm:flex">
        <button type="submit" class="inline-flex items-center justify-center rounded-full h-10 w-10 transition duration-500 ease-in-out text-white bg-blue-500 hover:bg-blue-400 focus:outline-none">
          <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" class="h-5 w-5 transform rotate-90">
            <path d="M10.894 2.553a1 1 0 00-1.788 0l-7 14a1 1 0 001.169 1.409l5-1.429A1 1 0 009 15.571V11a1 1 0 112 0v4.571a1 1 0 00.725.962l5 1.428a1 1 0 001.17-1.408l-7-14z"></path>
          </svg>
        </button>
      </div>
    </div>
  <% end %>
</turbo-frame>

app/views/messages/_message.html.erb
<div class="chat-message space-y-4">
  <div class="flex items-end">
    <div class="flex flex-col space-y-2 text-xs max-w-xs mx-2 order-2 items-start">
      <div>
        <span class="px-4 py-2 rounded-lg inline-block rounded-bl-none bg-slate-300 text-gray-600">
          <p class="text-gray-500"><%= message.author %></p>
          <%= message.content %>
        </span>
      </div>
    </div>
    <img src="https://images.unsplash.com/photo-1549078642-b2ba4bda0cdb?ixlib=rb-1.2.1&amp;ixid=eyJhcHBfaWQiOjEyMDd9&amp;auto=format&amp;fit=facearea&amp;facepad=3&amp;w=144&amp;h=144" alt="My profile" class="w-6 h-6 rounded-full order-1">
  </div>
</div>